MLIR: lib/Transforms/BufferResultsToOutParams.cpp File Reference
BufferResultsToOutParams.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/Passes.h"
Functions
static void updateFuncOp (FuncOp func, SmallVectorImpl< BlockArgument > &appendedEntryArgs)
static void updateReturnOps (FuncOp func, ArrayRef< BlockArgument > appendedEntryArgs)
static LogicalResult updateCalls (ModuleOp module)
Function Documentation
updateCalls()
static LogicalResult updateCalls (ModuleOp module) static
Definition at line 83 of file BufferResultsToOutParams.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Value::getType(), op, updateFuncOp(), and updateReturnOps().
updateFuncOp()
static void updateFuncOp (FuncOp func, SmallVectorImpl< BlockArgument > & appendedEntryArgs) static
Definition at line 22 of file BufferResultsToOutParams.cpp.
References mlir::detail::enumerate().
Referenced by updateCalls().
updateReturnOps()
static void updateReturnOps (FuncOp func, ArrayRef< BlockArgument > appendedEntryArgs) static
Definition at line 61 of file BufferResultsToOutParams.cpp.
References mlir::OpBuilder::create(), and op.
Referenced by updateCalls().